apiVersion: "pipelinesascode.tekton.dev/v1alpha1"
kind: Repository
metadata:
  name: w17guu5zu-java-springboot-gitops-repository
spec:
  url: https://github.com/rhtap-rhdh-qe/w17guu5zu-java-springboot-gitops